# Generated by Django 5.0.14 on 2025-04-21 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_stage", models.CharField(default="START", max_length=50)),
                ("final_syllabus_xml", models.TextField(blank=True, null=True)),
                ("explainer_system_prompt", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(blank=True, default="New Chat", max_length=200),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("model", "AI Model"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "message_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("message", "Standard Message"),
                            ("syllabus", "Syllabus Display"),
                            ("info", "Informational"),
                        ],
                        default="message",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "timestamp", "order"],
            },
        ),
    ]
