# Generated by Django 5.0.14 on 2025-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="explanation_start_index",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Index in ChatMessage history where the EXPLAINING stage began (0-based).",
                null=True,
            ),
        ),
    ]
