# Generated by Django 5.2 on 2025-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chatsession_explanation_start_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="resource_file_paths",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of server paths to processed text files from uploaded resources.",
                null=True,
            ),
        ),
    ]
