# Generated by Django 5.2 on 2025-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chatsession_resource_file_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="initial_resource_summary_for_manager",
            field=models.TextField(
                blank=True,
                help_text="The initial summary text provided to the conversation manager.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="processed_resource_content_json",
            field=models.TextField(
                blank=True,
                help_text="JSON string of raw text snippets (for RAW_TEXT type) or initial summaries.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="processed_resource_type",
            field=models.CharField(
                blank=True,
                help_text="Type of resource processing determined for syllabus generation.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="raw_data_for_dynamic_summary_json",
            field=models.TextField(
                blank=True,
                help_text="JSON string of the full uploaded resource data if type is SUMMARIES.",
                null=True,
            ),
        ),
    ]
