# Generated by Django 5.2 on 2025-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_chatsession_initial_resource_summary_for_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("message", "Standard Message"),
                    ("syllabus", "Syllabus Display"),
                    ("info", "Informational"),
                    ("internal", "Internal Command"),
                    ("internal_resource_summary", "Internal Resource Summary"),
                ],
                default="message",
                max_length=30,
                null=True,
            ),
        ),
    ]
