# Generated by Django 5.2 on 2025-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_chatmessage_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="original_resource_filenames",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of original filenames of resources uploaded with the first message.",
                null=True,
            ),
        ),
    ]
